# Taxi
***

## 1. Importing the needed libraries
```{r eval=FALSE, Packages}
library(dplyr)
library(ggplot2) # Data visualization
library(VIM)  # Plots missing data
library(mice)
library(ggthemes)
library(scales) # Scaling yaxis
library(caret)
library(ggcorrplot)
library(grid)
library(gridExtra)
library(corrplot)
library(stringr) # Split string on REGEX
library(RPostgreSQL) # Postgresql R Package
library(odbc)
```

https://www.rstudio.com/resources/videos/best-practices-for-working-with-databases-webinar/ 

```{r}
  
con <- dbConnect(odbc(),
                 driver = "PostgreSQL Driver",
                 database = "NYCTaxiDB",
                 uid = "wafic",
                 pwd = "a0310151",
                 server = "mypostgreinstance.czleyzmpydaj.eu-central-1.rds.amazonaws.com",
                 port = 5432)
```


## 2. Importing and Basic Exploting

```{r}
nycdb_dply <- src_postgres(
  host = 'mypostgreinstance.czleyzmpydaj.eu-central-1.rds.amazonaws.com',
  dbname = 'NYCTaxiDB',
  port = '5432',
  user = 'wafic',
  password = 'a0310151')
```


```{r}
src_tbls(nycdb_dply)
```

```{r}
train_1 <- tbl(nycdb_dply, 'train_data_1')
```

```{r}
train_1
```

```{r}

```

